### ISSUE TITLE
New job on EMIS backend fails with "Invalid database name '', allowed are: full, slice, dummy"

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/job-server#593] opened 2021-06-17 16:39 UTC
See https://jobs.opensafely.org/jobs/yf4pv4qkp45qmvfb/

**Comment by ghickman** [comment] 2021-06-18 07:42
This was caused by the changes in #584, however @inglesp has also raised the question of having the db field at all.  Given we only support one option, `full`, for new workspaces, is there a need to keep using field?  I think we probably want to keep the field for legacy workspaces, particularly those which have used the slice db, but is it worth the job-server API/job-runner/cohort-extractor(?) stopping use of the field?

@evansd and @sebbacon – you're probably best placed to answer this?

**Comment by evansd** [comment] 2021-06-18 09:07
@simon might have useful views here as well.

My instinct is that we should get rid of it. Though we will need job-server to keep returning a value in the field until we can update the NHSD backend.

**Comment by ghickman** [comment] 2021-08-20 13:20
Closing this since the original issue is fixed and we're talking about larger changes in #843

**Closed by ghickman** 2021-08-20 13:20 UTC
