### ISSUE TITLE
Surface Lack of Permissions to Run Jobs

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-server#1321] opened 2021-11-18 14:18 UTC
We've come across a handful of Users now who are set up with the correct permissions to run jobs, but lack access to any backends, so the run jobs view returns a 404.

Lets display but disable the run jobs button when a User doesn't have any of the necessary permissions with a short explainer on what they need, potentially even linking to the platform docs.

**Comment by lucyb** [comment] 2024-01-17 17:42
Closing as duplicate of #3989 .

**Closed by lucyb** 2024-01-17 17:42 UTC
