### ISSUE TITLE
`pg_restore` raises multiple warnings, sometimes 🙁

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#1338] opened 2021-11-19 11:30 UTC
*DEVELOPERS.md* suggests restoring a database dump with the following command:

```sh
pg_restore --clean --if-exists --no-acl --no-owner -d jobserver jobserver.dump
```

Under some circumstances, this command raises multiple warnings. It's not clear whether restoring the database dump was successful. [The docs][1] suggest that the `--clean --if-exists` combination means the warnings **aren't** harmless and, presumably, that restoring the database dump was not successful:

> `-c`
> `--clean`
> Clean (drop) database objects before recreating them. (Unless `--if-exists` is used, this might generate some harmless error messages, if any objects were not present in the destination database.)

The following three commands avoid the multiple warnings, but are verbose:

```sh
dropdb jobserver
createdb jobserver
pg_restore --no-acl --no-owner -d jobserver jobserver.dump
```

The docs suggest that the `--clean --create` combination would drop and create the database before restoring the database dump, combining the previous three commands in one command:

```sh
pg_restore --clean --create --no-acl --no-owner -d jobserver jobserver.dump
```

However, this command always raises multiple warnings.

Whilst this isn't a priority issue, I think it's worth investigating the circumstances under which the original command raises multiple warnings. @ghickman thinks the explanation is clashing PKs, which might happen when creating data in an empty database and then restoring a database dump into this database; the PKs of the created data might clash with the PKs of the database dump.

[1]: https://www.postgresql.org/docs/14/app-pgrestore.html

**Comment by evansd** [comment] 2021-11-19 11:42
Worth including what the warnings are, if you have them to hand.

**Comment by iaindillingham** [comment] 2021-11-19 11:52
It would. And I would, but I uncovered this whilst working on #1297 and subsequently lost them. Sorry 🙁

**Comment by ghickman** [comment] 2022-01-31 16:35
Without specific errors to look at I don't think this is really actionable.  Some things which might be of use:

* we're not using `--create` in the docs because it can fail with open db connections (eg a runserver)
* restoring a dump with primary keys (or I guess any unique field?) which clash will throw errors, but they're often ignorable
* worst case scenario you can always drop and create the database yourself before the restore, but always doing this would likely be unexpected behaviour (I think?)

I've added a note in #1574 about ignorable errors, but unless this is tripping anyone up I'm going to close it once #1574 is in.

**Closed** 2022-02-01 08:44 UTC
